# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_supermarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.IntegerField(choices=[('1', '言情'), ('2', '励志'), ('3', '玄幻'), ('4', '战争')], max_length=32, verbose_name='图书种类'),
        ),
    ]
