# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_supermarket', '0002_auto_20181108_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.IntegerField(choices=[(1, '言情'), (2, '励志'), (3, '玄幻'), (4, '战争')], verbose_name='图书种类'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(blank=True, null=True, verbose_name='密钥'),
        ),
    ]
