# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rbac', '0002_auto_20181107_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.ManyToManyField(to='Rbac.Role', verbose_name='所属角色'),
        ),
    ]
