# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rbac', '0004_auto_20181107_2013'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table=None,
        ),
        migrations.AlterModelTable(
            name='permission',
            table=None,
        ),
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
    ]
