# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='书名')),
                ('pub_time', models.DateTimeField(verbose_name='出版时间')),
                ('category', models.CharField(choices=[(1, '言情'), (2, '励志'), (3, '玄幻'), (4, '战争')], max_length=32, verbose_name='图书种类')),
            ],
            options={
                'verbose_name_plural': '图书表',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='出版社名称')),
            ],
            options={
                'verbose_name_plural': '出版社表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=18, verbose_name='密码')),
                ('token', models.CharField(blank=True, max_length=32, null=True, verbose_name='密钥')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='book_supermarket.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_supermarket.Publisher', verbose_name='出版社'),
        ),
    ]
