# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': '菜单表'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': '权限表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu',
            field=models.ManyToManyField(to='Rbac.Menu', verbose_name='所属菜单'),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='菜单表',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='权限表',
        ),
        migrations.AlterModelTable(
            name='role',
            table='角色表',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='用户表',
        ),
    ]
