# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rbac', '0005_auto_20181107_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='menu',
        ),
        migrations.AddField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rbac.Menu', verbose_name='所属菜单'),
        ),
    ]
