# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='os_distribution',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='系统厂商'),
        ),
    ]
